-- 코드를 작성해주세요
WITH  RECURSIVE RecursiveCTE AS (
    
    SELECT ID, PARENT_ID, 1 AS DEPTH FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT T.ID, T.PARENT_ID, C.DEPTH + 1 AS DEPTH FROM ECOLI_DATA T INNER JOIN RecursiveCTE C ON T.PARENT_ID = C.ID
)
SELECT ID FROM RecursiveCTE WHERE DEPTH = 3;